language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r22.0.1-linux.tgz
  - tar -zxf android-sdk_r22.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android list sdk
  - android -v update sdk --filter tools,platform-tools,android-17 --no-ui --force
